#!/usr/bin/env python3
"""Install this repo's workflows and reference skills into every agent harness.

The procedures live **once**, in `workflows/`. Each harness addresses skills its
own way and, hand-maintained, the copies drift — they already did once, which is
why this generator exists at all. It was born inside one project, generating
project-level wrappers; a procedure is not a property of a project, so it now
lives on the profile and generates into the harness *homes*.

Two kinds of thing are installed:

* **Workflows** (`workflows/*.md`) — YAML frontmatter describing the command,
  and a body that is the procedure. The harness gets a short generated wrapper
  that *points* at the body rather than copying it, so an edit takes effect
  without reinstalling and there is exactly one copy on disk.
* **Reference skills** (`skills/<name>/`) — ordinary Agent Skills, copied
  verbatim. They carry knowledge, not a procedure, so there is nothing to point
  at.

Files under `workflows/` with no frontmatter are sub-documents cited by a
workflow rather than invoked (see `references/`), and are skipped.

**Orphans are removed, but only ones we installed.** A harness home is not ours
the way a project directory was: it holds skills from plugins, from other tools
and from you. So every install writes a manifest of what it wrote, and removal
only ever considers paths named in the previous manifest.

A project checkout can take the same wrappers, written into its own skill
directories so a harness that scans the repo finds them. Those files are
generated pointers, not project-owned content: install also maintains a
managed block in the project's `.gitignore` covering exactly the paths it
added.

Usage::

    python scripts/gen_agent_wrappers.py            # install into harness homes
    python scripts/gen_agent_wrappers.py --check    # exit 1 if anything is stale
    python scripts/gen_agent_wrappers.py --repo DIR # install into a checkout
    python scripts/gen_agent_wrappers.py --self-test
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
WORKFLOWS = REPO / "workflows"
SKILLS = REPO / "skills"
HOME = Path.home()

MANIFEST = ".agent-workflows-manifest.json"
GITIGNORE_BEGIN = "# BEGIN agent-workflows"
GITIGNORE_END = "# END agent-workflows"

BANNER = (
    "<!-- GENERATED by agent-workflows/scripts/gen_agent_wrappers.py — DO NOT EDIT.\n"
    "     Edit {repo}/workflows/{name}.md and run `make install`. -->"
)


@dataclass(frozen=True)
class Harness:
    """One agent harness: where its skills live and what dialect it speaks."""

    key: str
    root: str  # relative to $HOME (profile) or the checkout (project)
    # Codex nests the argument hint under `metadata`; the others have nowhere to
    # put it.
    wants_metadata: bool = False
    # Codex additionally reads a per-skill interface descriptor.
    wants_openai_yaml: bool = False
    # Text rewrites for harnesses that address the same thing differently (a
    # command namespaced `/ns:cmd` for Claude Code is `/ns-cmd` for opencode).
    substitutions: tuple[tuple[str, str], ...] = field(default=())


# Only harnesses whose profile skill directory has been **confirmed on this
# machine** are listed. Guessing a path produces a skill that silently never
# loads and nothing anywhere that says so — which is worse than not installing.
# Adding one is a single entry plus zero content work.
HARNESSES = (
    Harness(key="claude", root=".claude/skills"),
    Harness(key="codex", root=".codex/skills", wants_metadata=True, wants_openai_yaml=True),
    # opencode addresses a *namespaced* command as `/ns-cmd` where Claude Code
    # writes `/ns:cmd`. None of this repo's workflows are namespaced, so there is
    # nothing to rewrite today — the hook stays because that difference is real
    # and a plugin-provided command would hit it. Confirmed: ~/.config/opencode
    # exists on this machine (opencode.jsonc).
    Harness(key="opencode", root=".config/opencode/skills"),
    # DeepSeek Harness scans ~/.dsh/skills (user-dsh) and ~/.agents/skills
    # (user-agents). ~/.dsh is the DSH-specific home, confirmed present
    # (settings.yaml). One level deep only: <root>/<name>/SKILL.md.
    Harness(key="dsh", root=".dsh/skills"),
)

# Project-level roots the same harnesses actually scan inside a checkout.
# DSH prefers `.agents/skills` here (the shared convention) over `.dsh/skills`,
# which would hide the files from anything else that follows that convention.
# OpenCode's project root is `.opencode/skills`, not `~/.config/opencode`.
PROJECT_HARNESSES = (
    Harness(key="claude", root=".claude/skills"),
    Harness(key="codex", root=".codex/skills", wants_metadata=True, wants_openai_yaml=True),
    Harness(key="opencode", root=".opencode/skills"),
    Harness(key="dsh", root=".agents/skills"),
)

REQUIRED = ("name", "description")


def canonical_repo() -> Path:
    """The primary checkout, even when this file is running from a worktree.

    Wrappers must point at one copy of the procedures. A worktree of *this*
    repo is for editing it, not for relocating every installed pointer.
    """
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--git-common-dir"],
            cwd=REPO,
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return REPO
    git_dir = Path(proc.stdout.strip())
    if not git_dir.is_absolute():
        git_dir = (REPO / git_dir).resolve()
    if git_dir.name == ".git":
        return git_dir.parent
    return REPO


def repo_label() -> str:
    """How the repo should be named to an agent reading a wrapper."""
    root = canonical_repo()
    try:
        return "~/" + str(root.relative_to(HOME))
    except ValueError:
        return str(root)


def parse_workflow(path: Path) -> dict | None:
    """Return a workflow's frontmatter, or None if it is a plain sub-document."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    _, _, rest = text.partition("---\n")
    front, sep, _ = rest.partition("\n---\n")
    if not sep:
        raise SystemExit(f"{path.relative_to(REPO)}: frontmatter is not closed by `---`")

    meta = yaml.safe_load(front) or {}
    if not isinstance(meta, dict):
        raise SystemExit(f"{path.relative_to(REPO)}: frontmatter must be a mapping")

    missing = [k for k in REQUIRED if not meta.get(k)]
    if missing:
        raise SystemExit(f"{path.relative_to(REPO)}: frontmatter missing {', '.join(missing)}")
    if meta["name"] != path.stem:
        raise SystemExit(
            f"{path.relative_to(REPO)}: frontmatter name {meta['name']!r} must match "
            f"the filename ({path.stem!r}) — every harness keys the skill by its directory."
        )
    return meta


def wrapper_body(meta: dict) -> str:
    """The pointer every harness gets. All of them say the same thing."""
    name = meta["name"]
    repo = repo_label()
    title = meta.get("display_name") or name.replace("-", " ").title()
    note = (meta.get("wrapper_note") or "").strip()

    parts = [
        BANNER.format(name=name, repo=repo),
        "",
        f"# {title}",
        "",
        "This procedure is repo-independent and lives in one place. Read these two",
        "files, in this order, before doing anything:",
        "",
        f"1. `{repo}/references/project-overlay.md` — how to find the current",
        "   project's bindings, and what to do when it has none.",
        f"2. `{repo}/workflows/{name}.md` — the procedure. Follow it exactly,",
        "   treating the argument above as its input.",
        "",
        "**Conflict rule.** The project's overlay wins on *bindings* — names,",
        "commands, hosts, labels, paths. This procedure wins on *steps*. The",
        "project's own conventions document wins on *engineering invariants*. Two",
        "documents disagreeing about a step is a bug in the docs, not a judgment",
        "call for you: say so instead of picking one.",
    ]
    if note:
        parts += ["", note]
    return "\n".join(parts) + "\n"


def _derive_prompt(meta: dict) -> str:
    """"Take one issue to a PR" + "[issue number]" -> a sentence Codex can show.

    Only the first character is lowered — `short_description` may legitimately
    open with a proper noun, and `.lower()` would flatten the whole line.
    """
    summary = str(meta.get("short_description") or meta["description"]).strip().rstrip(".")
    summary = summary[:1].lower() + summary[1:]
    prompt = f"Use ${meta['name']} to {summary}."
    if hint := meta.get("argument-hint"):
        prompt += f" Argument: {hint}"
    return prompt


def render_workflow(meta: dict, harness: Harness) -> dict[Path, str]:
    """Every file this harness needs for this workflow, keyed by $HOME-relative path."""
    name = meta["name"]
    front: dict = {"name": name, "description": str(meta["description"]).strip()}
    if harness.wants_metadata and meta.get("argument-hint"):
        front["metadata"] = {"argument-hint": meta["argument-hint"]}

    dumped = yaml.safe_dump(front, sort_keys=False, allow_unicode=True, width=88)
    skill = f"---\n{dumped}---\n\n{wrapper_body(meta)}"

    out: dict[Path, str] = {}
    base = Path(harness.root) / name
    out[base / "SKILL.md"] = skill

    if harness.wants_openai_yaml:
        default_prompt = meta.get("default_prompt") or _derive_prompt(meta)
        interface = {
            "interface": {
                "display_name": meta.get("display_name") or name.replace("-", " ").title(),
                "short_description": meta.get("short_description") or meta["description"],
                "default_prompt": default_prompt,
            }
        }
        out[base / "agents" / "openai.yaml"] = yaml.safe_dump(
            interface, sort_keys=False, allow_unicode=True, width=88
        )

    for old, new in harness.substitutions:
        out = {p: t.replace(old, new) for p, t in out.items()}
    return out


def render_reference_skills(harness: Harness) -> dict[Path, str]:
    """Reference skills are copied verbatim — they carry knowledge, not steps."""
    out: dict[Path, str] = {}
    for skill_dir in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        for src in sorted(skill_dir.rglob("*")):
            if not src.is_file() or src.name == ".DS_Store":
                continue
            rel = src.relative_to(SKILLS)
            out[Path(harness.root) / rel] = src.read_text(encoding="utf-8")
    return out


def expected(harnesses: tuple[Harness, ...] = HARNESSES) -> dict[Path, str]:
    """Every file we install, for every harness, keyed by root-relative path."""
    out: dict[Path, str] = {}
    for harness in harnesses:
        out.update(render_reference_skills(harness))
        for path in sorted(WORKFLOWS.glob("*.md")):
            meta = parse_workflow(path)
            if meta is None:
                continue
            out.update(render_workflow(meta, harness))
    return out


def previously_installed(base: Path, harnesses: tuple[Harness, ...]) -> set[Path]:
    """What the last install wrote — the only paths we may ever remove."""
    found: set[Path] = set()
    for harness in harnesses:
        manifest = base / harness.root / MANIFEST
        if not manifest.exists():
            continue
        try:
            names = json.loads(manifest.read_text(encoding="utf-8"))["files"]
        except (json.JSONDecodeError, KeyError, TypeError):
            print(f"warning: unreadable manifest at {manifest}", file=sys.stderr)
            continue
        found |= {Path(n) for n in names}
    return found


def write_manifests(base: Path, harnesses: tuple[Harness, ...], want: dict[Path, str]) -> None:
    for harness in harnesses:
        root = Path(harness.root)
        mine = sorted(str(p) for p in want if p.is_relative_to(root))
        target = base / root / MANIFEST
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps({"generated_by": str(canonical_repo()), "files": mine}, indent=2) + "\n",
            encoding="utf-8",
        )


def _manifest_stale(base: Path, harness: Harness, want: dict[Path, str]) -> bool:
    """A manifest that does not list exactly what we now install cannot clean up.

    Missing counts as stale: without it the next run has no record of what it
    wrote, so an orphan would survive for ever.
    """
    manifest = base / harness.root / MANIFEST
    if not manifest.exists():
        return True
    try:
        listed = json.loads(manifest.read_text(encoding="utf-8"))["files"]
    except (json.JSONDecodeError, KeyError, TypeError):
        return True
    root = Path(harness.root)
    return listed != sorted(str(p) for p in want if p.is_relative_to(root))


def _read(base: Path, path: Path) -> str | None:
    full = base / path
    return full.read_text(encoding="utf-8") if full.is_file() else None


def _display(base: Path, path: Path) -> str:
    if base == HOME:
        return f"~/{path}"
    return str(path)


def _prune_empty_dirs(base: Path, harnesses: tuple[Harness, ...]) -> None:
    """Renaming a workflow leaves its directory behind; take that too."""
    for harness in harnesses:
        root = base / harness.root
        if not root.exists():
            continue
        for d in sorted(root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
            if d.is_dir() and not any(d.iterdir()):
                d.rmdir()


def apply_install(
    base: Path,
    harnesses: tuple[Harness, ...],
    *,
    check: bool,
    fix_hint: str = "Fix: run `make install`.",
) -> int:
    """Write or verify wrappers under `base`. Return a process exit code."""
    want = expected(harnesses)
    stale = [p for p, text in want.items() if _read(base, p) != text]
    orphans = sorted(previously_installed(base, harnesses) - set(want))
    manifests_stale = [h.key for h in harnesses if _manifest_stale(base, h, want)]

    if check:
        if stale or orphans or manifests_stale:
            for p in stale:
                print(f"stale: {_display(base, p)}", file=sys.stderr)
            for p in orphans:
                print(f"orphaned (no longer generated): {_display(base, p)}", file=sys.stderr)
            for k in manifests_stale:
                print(f"manifest out of date: {k}", file=sys.stderr)
            print(f"\n{fix_hint}", file=sys.stderr)
            return 1
        print(f"agent harnesses are up to date ({len(want)} files)")
        return 0

    for path in stale:
        full = base / path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(want[path], encoding="utf-8")
        print(f"wrote {_display(base, path)}")
    for path in orphans:
        full = base / path
        if full.exists():
            full.unlink()
            print(f"removed {_display(base, path)}")
    write_manifests(base, harnesses, want)
    _prune_empty_dirs(base, harnesses)

    print(f"{len(stale)} written, {len(orphans)} removed, {len(want)} total")
    return 0


def gitignore_paths(want: dict[Path, str], harnesses: tuple[Harness, ...]) -> list[str]:
    """Root-anchored gitignore entries covering exactly what we add."""
    entries: set[str] = set()
    for path in want:
        parts = path.parts
        if len(parts) >= 3:
            entries.add("/" + "/".join(parts[:3]) + "/")
    for harness in harnesses:
        entries.add("/" + Path(harness.root).as_posix() + "/" + MANIFEST)
    return sorted(entries)


def render_gitignore_block(entries: list[str]) -> str:
    return (
        "\n".join(
            [
                GITIGNORE_BEGIN,
                "# Generated skill wrappers — do not commit. Refresh with:",
                f"#   python3 {repo_label()}/scripts/gen_agent_wrappers.py --repo .",
                *entries,
                GITIGNORE_END,
            ]
        )
        + "\n"
    )


def replace_or_append_block(existing: str, block: str) -> str:
    """Insert or replace the managed gitignore block. Preserve everything else."""
    if GITIGNORE_BEGIN in existing:
        start = existing.find(GITIGNORE_BEGIN)
        end = existing.find(GITIGNORE_END, start)
        if end == -1:
            prefix = existing[:start].rstrip()
            return (prefix + "\n\n" + block) if prefix else block
        end += len(GITIGNORE_END)
        if end < len(existing) and existing[end] == "\n":
            end += 1
        return existing[:start] + block + existing[end:]
    if not existing:
        return block
    if existing.endswith("\n"):
        return existing + "\n" + block
    return existing + "\n\n" + block


def ensure_gitignore(repo: Path, entries: list[str]) -> str:
    """Write the managed block. Return wrote / updated / unchanged."""
    path = repo / ".gitignore"
    block = render_gitignore_block(entries)
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    updated = replace_or_append_block(existing, block)
    if updated == existing:
        return "unchanged"
    path.write_text(updated, encoding="utf-8")
    return "wrote" if not existing else "updated"


def gitignore_stale(repo: Path, entries: list[str]) -> bool:
    path = repo / ".gitignore"
    if not path.is_file():
        return True
    return render_gitignore_block(entries) not in path.read_text(encoding="utf-8")


def tracked_installed_paths(
    repo: Path, want: dict[Path, str], harnesses: tuple[Harness, ...]
) -> list[str]:
    """Installed paths that git already tracks — gitignore will not hide them."""
    names = {path.as_posix() for path in want}
    for harness in harnesses:
        names.add(Path(harness.root).as_posix() + "/" + MANIFEST)
    try:
        proc = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=repo,
            check=True,
            capture_output=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    tracked = {p.decode() for p in proc.stdout.split(b"\0") if p}
    return sorted(names & tracked)


def install_into_repo(repo: Path, *, check: bool = False) -> int:
    """Install wrappers into a checkout and keep them gitignored."""
    want = expected(PROJECT_HARNESSES)
    entries = gitignore_paths(want, PROJECT_HARNESSES)
    hint = f"Fix: run `python3 {repo_label()}/scripts/gen_agent_wrappers.py --repo {repo}`."
    rc = apply_install(repo, PROJECT_HARNESSES, check=check, fix_hint=hint)
    if check:
        if gitignore_stale(repo, entries):
            print("gitignore block missing or stale", file=sys.stderr)
            print(f"\n{hint}", file=sys.stderr)
            return 1
        return rc

    if rc != 0:
        return rc

    action = ensure_gitignore(repo, entries)
    if action != "unchanged":
        print(f"{action} {repo / '.gitignore'}")

    tracked = tracked_installed_paths(repo, want, PROJECT_HARNESSES)
    if tracked:
        print(
            "warning: generated wrappers are tracked; gitignore will not hide them:",
            file=sys.stderr,
        )
        for path in tracked:
            print(f"  {path}", file=sys.stderr)
        print("  fix: git rm -r --cached -- <paths>", file=sys.stderr)
    return 0


def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)


def self_test() -> int:
    """Prove a repo install writes wrappers and gitignores exactly those files."""
    failed = 0

    existing = "node_modules/\n.env\n"
    block = render_gitignore_block(["/.claude/skills/work-issue/"])
    merged = replace_or_append_block(existing, block)
    if "node_modules/" not in merged or GITIGNORE_BEGIN not in merged:
        print("replace_or_append_block dropped existing ignore rules", file=sys.stderr)
        failed += 1
    again = replace_or_append_block(merged, render_gitignore_block(["/.agents/skills/work-issue/"]))
    if again.count(GITIGNORE_BEGIN) != 1 or "/.claude/skills/work-issue/" in again:
        print("replace_or_append_block did not replace the managed block", file=sys.stderr)
        failed += 1
    if replace_or_append_block(block, block) != block:
        print("replace_or_append_block is not idempotent", file=sys.stderr)
        failed += 1

    with tempfile.TemporaryDirectory() as tmp:
        repo = Path(tmp)
        if _git(repo, "init").returncode != 0:
            print("self-test: git init failed", file=sys.stderr)
            return 1
        (repo / ".gitignore").write_text("# keep me\n/dist/\n", encoding="utf-8")
        (repo / "docs").mkdir()
        (repo / "docs" / "agent-overlay.yaml").write_text("schema: 1\n", encoding="utf-8")
        foreign = repo / ".claude" / "skills" / "other" / "SKILL.md"
        foreign.parent.mkdir(parents=True)
        foreign.write_text("mine\n", encoding="utf-8")

        if install_into_repo(repo) != 0:
            print("self-test: install_into_repo failed", file=sys.stderr)
            return 1

        want = expected(PROJECT_HARNESSES)
        missing = [p for p in want if not (repo / p).is_file()]
        if missing:
            print(f"self-test: missing wrappers: {missing[:3]}", file=sys.stderr)
            failed += 1

        sample = next(iter(want))
        ignored = _git(repo, "check-ignore", "-q", "--", str(sample))
        if ignored.returncode != 0:
            print(f"self-test: {sample} is not gitignored", file=sys.stderr)
            failed += 1

        overlay = _git(repo, "check-ignore", "-q", "--", "docs/agent-overlay.yaml")
        if overlay.returncode != 1:
            print("self-test: overlay must not be gitignored", file=sys.stderr)
            failed += 1

        keep = _git(repo, "check-ignore", "-q", "--", ".claude/skills/other/SKILL.md")
        if keep.returncode != 1:
            print("self-test: a foreign skill must not be gitignored", file=sys.stderr)
            failed += 1
        if foreign.read_text(encoding="utf-8") != "mine\n":
            print("self-test: overwrote a skill we did not install", file=sys.stderr)
            failed += 1

        text = (repo / ".gitignore").read_text(encoding="utf-8")
        if "# keep me" not in text or "/dist/" not in text:
            print("self-test: lost existing .gitignore content", file=sys.stderr)
            failed += 1
        if GITIGNORE_BEGIN not in text or GITIGNORE_END not in text:
            print("self-test: missing managed gitignore block", file=sys.stderr)
            failed += 1

        status = _git(repo, "status", "--porcelain", "--untracked-files=all")
        untracked = {
            line[3:]
            for line in status.stdout.splitlines()
            if line.startswith("?? ")
        }
        leaked = [p.as_posix() for p in want if p.as_posix() in untracked]
        if leaked:
            print(f"self-test: wrappers still untracked: {leaked[:3]}", file=sys.stderr)
            failed += 1
        if ".gitignore" not in untracked:
            print("self-test: .gitignore itself should remain visible to git", file=sys.stderr)
            failed += 1

        if install_into_repo(repo) != 0:
            print("self-test: second install failed", file=sys.stderr)
            failed += 1
        if install_into_repo(repo, check=True) != 0:
            print("self-test: --check after install should be clean", file=sys.stderr)
            failed += 1

    if failed:
        return 1
    print("gen_agent_wrappers self-test passed")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if anything is stale")
    ap.add_argument(
        "--repo",
        type=Path,
        help="install wrappers into this checkout and gitignore them",
    )
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="assert a repo install gitignores the files it added, and exit",
    )
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if args.repo is not None:
        repo = args.repo.resolve()
        if not (repo / ".git").exists():
            print(f"{repo}: not a git checkout (no .git)", file=sys.stderr)
            return 2
        return install_into_repo(repo, check=args.check)

    return apply_install(HOME, HARNESSES, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
