#!/usr/bin/env python3
"""Install this repo's workflows and reference skills into every agent harness.

The procedures live **once**, in `workflows/`. Each harness addresses skills its
own way and, hand-maintained, the copies drift — they already did once, which is
why this generator exists at all. It was born inside one project, generating
project-level wrappers; a procedure is not a property of a project, so it now
lives on the profile and generates into the harness *homes*.

Two kinds of thing are installed:

* **Workflows** (`workflows/*.md`) — YAML frontmatter describing the command,
  and a body that is the procedure. The harness gets a short generated wrapper
  that *points* at the body rather than copying it, so an edit takes effect
  without reinstalling and there is exactly one copy on disk.
* **Reference skills** (`skills/<name>/`) — ordinary Agent Skills, copied
  verbatim. They carry knowledge, not a procedure, so there is nothing to point
  at.

Files under `workflows/` with no frontmatter are sub-documents cited by a
workflow rather than invoked (see `references/`), and are skipped.

**Orphans are removed, but only ones we installed.** A harness home is not ours
the way a project directory was: it holds skills from plugins, from other tools
and from you. So every install writes a manifest of what it wrote, and removal
only ever considers paths named in the previous manifest.

Usage::

    python scripts/gen_agent_wrappers.py            # install
    python scripts/gen_agent_wrappers.py --check    # exit 1 if anything is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
WORKFLOWS = REPO / "workflows"
SKILLS = REPO / "skills"
HOME = Path.home()

MANIFEST = ".agent-workflows-manifest.json"

BANNER = (
    "<!-- GENERATED by agent-workflows/scripts/gen_agent_wrappers.py — DO NOT EDIT.\n"
    "     Edit {repo}/workflows/{name}.md and run `make install`. -->"
)


@dataclass(frozen=True)
class Harness:
    """One agent harness: where its profile skills live and what dialect it speaks."""

    key: str
    root: str  # relative to $HOME
    # Codex nests the argument hint under `metadata`; the others have nowhere to
    # put it.
    wants_metadata: bool = False
    # Codex additionally reads a per-skill interface descriptor.
    wants_openai_yaml: bool = False
    # Text rewrites for harnesses that address the same thing differently (a
    # command namespaced `/ns:cmd` for Claude Code is `/ns-cmd` for opencode).
    substitutions: tuple[tuple[str, str], ...] = field(default=())


# Only harnesses whose profile skill directory has been **confirmed on this
# machine** are listed. Guessing a path produces a skill that silently never
# loads and nothing anywhere that says so — which is worse than not installing.
# Adding one is a single entry plus zero content work.
HARNESSES = (
    Harness(key="claude", root=".claude/skills"),
    Harness(key="codex", root=".codex/skills", wants_metadata=True, wants_openai_yaml=True),
    # opencode addresses a *namespaced* command as `/ns-cmd` where Claude Code
    # writes `/ns:cmd`. None of this repo's workflows are namespaced, so there is
    # nothing to rewrite today — the hook stays because that difference is real
    # and a plugin-provided command would hit it. Confirmed: ~/.config/opencode
    # exists on this machine (opencode.jsonc).
    Harness(key="opencode", root=".config/opencode/skills"),
    # DeepSeek Harness scans ~/.dsh/skills (user-dsh) and ~/.agents/skills
    # (user-agents). ~/.dsh is the DSH-specific home, confirmed present
    # (settings.yaml). One level deep only: <root>/<name>/SKILL.md.
    Harness(key="dsh", root=".dsh/skills"),
)

REQUIRED = ("name", "description")


def repo_label() -> str:
    """How the repo should be named to an agent reading a wrapper."""
    try:
        return "~/" + str(REPO.relative_to(HOME))
    except ValueError:
        return str(REPO)


def parse_workflow(path: Path) -> dict | None:
    """Return a workflow's frontmatter, or None if it is a plain sub-document."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    _, _, rest = text.partition("---\n")
    front, sep, _ = rest.partition("\n---\n")
    if not sep:
        raise SystemExit(f"{path.relative_to(REPO)}: frontmatter is not closed by `---`")

    meta = yaml.safe_load(front) or {}
    if not isinstance(meta, dict):
        raise SystemExit(f"{path.relative_to(REPO)}: frontmatter must be a mapping")

    missing = [k for k in REQUIRED if not meta.get(k)]
    if missing:
        raise SystemExit(f"{path.relative_to(REPO)}: frontmatter missing {', '.join(missing)}")
    if meta["name"] != path.stem:
        raise SystemExit(
            f"{path.relative_to(REPO)}: frontmatter name {meta['name']!r} must match "
            f"the filename ({path.stem!r}) — every harness keys the skill by its directory."
        )
    return meta


def wrapper_body(meta: dict) -> str:
    """The pointer every harness gets. All of them say the same thing."""
    name = meta["name"]
    repo = repo_label()
    title = meta.get("display_name") or name.replace("-", " ").title()
    note = (meta.get("wrapper_note") or "").strip()

    parts = [
        BANNER.format(name=name, repo=repo),
        "",
        f"# {title}",
        "",
        "This procedure is repo-independent and lives in one place. Read these two",
        "files, in this order, before doing anything:",
        "",
        f"1. `{repo}/references/project-overlay.md` — how to find the current",
        "   project's bindings, and what to do when it has none.",
        f"2. `{repo}/workflows/{name}.md` — the procedure. Follow it exactly,",
        "   treating the argument above as its input.",
        "",
        "**Conflict rule.** The project's overlay wins on *bindings* — names,",
        "commands, hosts, labels, paths. This procedure wins on *steps*. The",
        "project's own conventions document wins on *engineering invariants*. Two",
        "documents disagreeing about a step is a bug in the docs, not a judgment",
        "call for you: say so instead of picking one.",
    ]
    if note:
        parts += ["", note]
    return "\n".join(parts) + "\n"


def _derive_prompt(meta: dict) -> str:
    """"Take one issue to a PR" + "[issue number]" -> a sentence Codex can show.

    Only the first character is lowered — `short_description` may legitimately
    open with a proper noun, and `.lower()` would flatten the whole line.
    """
    summary = str(meta.get("short_description") or meta["description"]).strip().rstrip(".")
    summary = summary[:1].lower() + summary[1:]
    prompt = f"Use ${meta['name']} to {summary}."
    if hint := meta.get("argument-hint"):
        prompt += f" Argument: {hint}"
    return prompt


def render_workflow(meta: dict, harness: Harness) -> dict[Path, str]:
    """Every file this harness needs for this workflow, keyed by $HOME-relative path."""
    name = meta["name"]
    front: dict = {"name": name, "description": str(meta["description"]).strip()}
    if harness.wants_metadata and meta.get("argument-hint"):
        front["metadata"] = {"argument-hint": meta["argument-hint"]}

    dumped = yaml.safe_dump(front, sort_keys=False, allow_unicode=True, width=88)
    skill = f"---\n{dumped}---\n\n{wrapper_body(meta)}"

    out: dict[Path, str] = {}
    base = Path(harness.root) / name
    out[base / "SKILL.md"] = skill

    if harness.wants_openai_yaml:
        default_prompt = meta.get("default_prompt") or _derive_prompt(meta)
        interface = {
            "interface": {
                "display_name": meta.get("display_name") or name.replace("-", " ").title(),
                "short_description": meta.get("short_description") or meta["description"],
                "default_prompt": default_prompt,
            }
        }
        out[base / "agents" / "openai.yaml"] = yaml.safe_dump(
            interface, sort_keys=False, allow_unicode=True, width=88
        )

    for old, new in harness.substitutions:
        out = {p: t.replace(old, new) for p, t in out.items()}
    return out


def render_reference_skills(harness: Harness) -> dict[Path, str]:
    """Reference skills are copied verbatim — they carry knowledge, not steps."""
    out: dict[Path, str] = {}
    for skill_dir in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        for src in sorted(skill_dir.rglob("*")):
            if not src.is_file() or src.name == ".DS_Store":
                continue
            rel = src.relative_to(SKILLS)
            out[Path(harness.root) / rel] = src.read_text(encoding="utf-8")
    return out


def expected() -> dict[Path, str]:
    """Every file we install, for every harness, keyed by $HOME-relative path."""
    out: dict[Path, str] = {}
    for harness in HARNESSES:
        out.update(render_reference_skills(harness))
        for path in sorted(WORKFLOWS.glob("*.md")):
            meta = parse_workflow(path)
            if meta is None:
                continue
            out.update(render_workflow(meta, harness))
    return out


def previously_installed() -> set[Path]:
    """What the last install wrote — the only paths we may ever remove."""
    found: set[Path] = set()
    for harness in HARNESSES:
        manifest = HOME / harness.root / MANIFEST
        if not manifest.exists():
            continue
        try:
            names = json.loads(manifest.read_text(encoding="utf-8"))["files"]
        except (json.JSONDecodeError, KeyError, TypeError):
            print(f"warning: unreadable manifest at {manifest}", file=sys.stderr)
            continue
        found |= {Path(n) for n in names}
    return found


def write_manifests(want: dict[Path, str]) -> None:
    for harness in HARNESSES:
        root = Path(harness.root)
        mine = sorted(str(p) for p in want if p.is_relative_to(root))
        target = HOME / root / MANIFEST
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps({"generated_by": str(REPO), "files": mine}, indent=2) + "\n",
            encoding="utf-8",
        )


def _manifest_stale(harness: Harness, want: dict[Path, str]) -> bool:
    """A manifest that does not list exactly what we now install cannot clean up.

    Missing counts as stale: without it the next run has no record of what it
    wrote, so an orphan would survive for ever.
    """
    manifest = HOME / harness.root / MANIFEST
    if not manifest.exists():
        return True
    try:
        listed = json.loads(manifest.read_text(encoding="utf-8"))["files"]
    except (json.JSONDecodeError, KeyError, TypeError):
        return True
    root = Path(harness.root)
    return listed != sorted(str(p) for p in want if p.is_relative_to(root))


def _read(path: Path) -> str | None:
    full = HOME / path
    return full.read_text(encoding="utf-8") if full.is_file() else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if anything is stale")
    args = ap.parse_args()

    want = expected()
    stale = [p for p, text in want.items() if _read(p) != text]
    orphans = sorted(previously_installed() - set(want))
    manifests_stale = [h.key for h in HARNESSES if _manifest_stale(h, want)]

    if args.check:
        if stale or orphans or manifests_stale:
            for p in stale:
                print(f"stale: ~/{p}", file=sys.stderr)
            for p in orphans:
                print(f"orphaned (no longer generated): ~/{p}", file=sys.stderr)
            for k in manifests_stale:
                print(f"manifest out of date: {k}", file=sys.stderr)
            print("\nFix: run `make install`.", file=sys.stderr)
            return 1
        print(f"agent harnesses are up to date ({len(want)} files)")
        return 0

    for path in stale:
        full = HOME / path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(want[path], encoding="utf-8")
        print(f"wrote ~/{path}")
    for path in orphans:
        full = HOME / path
        if full.exists():
            full.unlink()
            print(f"removed ~/{path}")
    write_manifests(want)
    _prune_empty_dirs()

    print(f"{len(stale)} written, {len(orphans)} removed, {len(want)} total")
    return 0


def _prune_empty_dirs() -> None:
    """Renaming a workflow leaves its directory behind; take that too."""
    for harness in HARNESSES:
        root = HOME / harness.root
        if not root.exists():
            continue
        for d in sorted(root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
            if d.is_dir() and not any(d.iterdir()):
                d.rmdir()


if __name__ == "__main__":
    raise SystemExit(main())
